# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170310_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gas',
        ),
        migrations.AddField(
            model_name='order',
            name='gas_name',
            field=models.CharField(default='El gazo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='gas_price',
            field=models.FloatField(default=23.45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
