# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170310_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
