# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170310_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date_refill', 'user')},
        ),
    ]
