# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170311_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gas',
            name='is_valide',
        ),
    ]
