# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_is_valide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('is_valide', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='gaz_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gaz_price',
        ),
        migrations.AddField(
            model_name='order',
            name='gaz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Gaz'),
            preserve_default=False,
        ),
    ]
